/* eslint no-undef: 'off' */

module.export = {
  link: '#cbc065',
  linkHovered: '#fff495',
  bodyBackgroundColor: '#171717',
  headerBackgroundColor: '#322c27',
  footerBackgroundColor: '#3e3025',
  footerTextColor: '#cfb095',
  orangeTextColor: '#ac6b37',
  orangeBrightTextColor: '#e4991c',
  menuButtonBackgroundColor: '#252525',
  contentHolderHeaderColor: '#564b41',
  forumSubForumTopicContainerSeparatorBackgroundColor: '#9c877c',
  contentHolderBodyColor: '#48423d',
  contentHolderBodyBackgroundColor: '#7b736b',
  breadcrumbBackgroundColor: 'bodyBackgroundColor',
  breadcrumbItemBackgroundColorHovered: 'contentHolderHeaderColor',
  breadcrumbItemBackgroundColor: '#5d5956',
  breadcrumbBorderColor: 'headerBackgroundColor',
  bbCodeOfftopicColor: '#67605a',
  bbCodeQuoteBorderColor: '#d4c5b6',
  bbCodeThinkBorderColor: '#ffffff',
  bbCodeThinkBackgroundColor: '#d4c5b6',
  bbCodeQuoteBackgroundColor: '#9a8d7f',
  bbCodeCodeHeaderColor: '#d4d4d4',
  bbCodeCodeContentColor: '#ffa100',
  bbCodeCodeBorderColor: '#9c9085',
  bbCodeCodeBackgroundColor: '#59534d'
};
