// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/tether/tether.d.ts
declare class Tether {
    constructor(options: Tether.ITetherOptions);

    public setOptions(options: Tether.ITetherOptions): void;
    public disable(): void;
    public enable(): void;
    public destroy(): void;
    public position(): void;

    public static position(): void;
}

declare namespace Tether {
    interface ITetherOptions {
        attachment?: string;
        classes?: {[className: string]: boolean};
        classPrefix?: string;
        constraints?: ITetherConstraint[];
        element?: HTMLElement | string | any /* JQuery */;
        enabled?: boolean;
        offset?: string;
        optimizations?: any;
        target?: HTMLElement | string | any /* JQuery */;
        targetAttachment?: string;
        targetOffset?: string;
        targetModifier?: string;
    }

    interface ITetherConstraint {
        attachment?: string;
        outOfBoundsClass?: string;
        pin?: boolean | string[];
        pinnedClass?: string;
        to?: string | HTMLElement | number[];
    }
}

declare module "tether" {
    export = Tether;
}