const GET_NAVIGATIONLINKS = "GET_NAVIGATIONLINKS";
const GET_NAVIGATIONLINKS_SUCCESS = "GET_NAVIGATIONLINKS_SUCCESS";

const GET_ALL_CHAPTERS = "GET_ALL_CHAPTERS";
const GET_ALL_CHAPTERS_SUCCESS = "GET_ALL_CHAPTERS_SUCCESS";

const GET_ALL_FORUMS = "GET_ALL_FORUMS";
const GET_ALL_FORUMS_SUCCESS = "GET_ALL_FORUMS_SUCCESS";

export {
  GET_NAVIGATIONLINKS,
  GET_NAVIGATIONLINKS_SUCCESS,
  GET_ALL_CHAPTERS,
  GET_ALL_CHAPTERS_SUCCESS,
  GET_ALL_FORUMS,
  GET_ALL_FORUMS_SUCCESS
};
