const GET_ALL_FORUMS = "GET_ALL_FORUMS";
const GET_ALL_FORUMS_SUCCESS = "GET_ALL_FORUMS_SUCCESS";

const GET_ALL_AUTHORS = "GET_ALL_AUTHORS";
const GET_ALL_AUTHORS_SUCCESS = "GET_ALL_AUTHORS_SUCCESS";

const GET_NAVIGATIONLINKS = "GET_NAVIGATIONLINKS";
const GET_NAVIGATIONLINKS_SUCCESS = "GET_NAVIGATIONLINKS_SUCCESS";

export {
    GET_ALL_FORUMS,
    GET_ALL_FORUMS_SUCCESS,
    GET_ALL_AUTHORS,
    GET_ALL_AUTHORS_SUCCESS,
    GET_NAVIGATIONLINKS,
    GET_NAVIGATIONLINKS_SUCCESS
};
