const GET_NAVIGATIONLINKS = "GET_NAVIGATIONLINKS";
const GET_NAVIGATIONLINKS_SUCCESS = "GET_NAVIGATIONLINKS_SUCCESS";

const GET_ALL_CHAPTERS = "GET_ALL_CHAPTERS";
const GET_ALL_CHAPTERS_SUCCESS = "GET_ALL_CHAPTERS_SUCCESS";
const GET_CHAPTER_BY_ID = "GET_CHAPTER_BY_ID";
const GET_CHAPTER_BY_ID_SUCCESS = "GET_CHAPTER_BY_ID_SUCCESS";

const GET_FORUMS_BY_CHAPTER_ID = "GET_FORUMS_BY_CHAPTER_ID";
const GET_FORUMS_BY_CHAPTER_ID_SUCCESS = "GET_FORUMS_BY_CHAPTER_ID_SUCCESS";

const GET_LAST_ACTIVE_TOPICS = "GET_LAST_ACTIVE_TOPICS";
const GET_LAST_ACTIVE_TOPICS_SUCCESS = "GET_LAST_ACTIVE_TOPICS_SUCCESS";

const GET_TOPICS_BY_FORUM_ID = "GET_TOPICS_BY_FORUM_ID";
const GET_TOPICS_BY_FORUM_ID_SUCCESS = "GET_TOPICS_BY_FORUM_ID_SUCCESS";

const GET_LOCALE = "GET_LOCALE";
const GET_LOCALE_SUCCESS = "GET_LOCALE_SUCCESS";

const GET_SOCIALMEDIALINKS = "GET_SOCIALMEDIALINKS";
const GET_SOCIALMEDIALINKS_SUCCESS = "GET_SOCIALMEDIALINKS_SUCCESS";

const ADD_NOTIFICATION = "ADD_NOTIFICATION";
const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

const GET_FORUM_BREADCRUMBS = "GET_FORUM_BREADCRUMBS";
const GET_TOPIC_BREADCRUMBS = "GET_TOPIC_BREADCRUMBS";
const GET_BREADCRUMBS_SUCCESS = "GET_BREADCRUMBS_SUCCESS";

export {
  GET_NAVIGATIONLINKS,
  GET_NAVIGATIONLINKS_SUCCESS,
  GET_ALL_CHAPTERS,
  GET_ALL_CHAPTERS_SUCCESS,
  GET_CHAPTER_BY_ID,
  GET_CHAPTER_BY_ID_SUCCESS,
  GET_FORUMS_BY_CHAPTER_ID,
  GET_FORUMS_BY_CHAPTER_ID_SUCCESS,
  GET_LAST_ACTIVE_TOPICS,
  GET_LAST_ACTIVE_TOPICS_SUCCESS,
  GET_TOPICS_BY_FORUM_ID,
  GET_TOPICS_BY_FORUM_ID_SUCCESS,
  GET_LOCALE,
  GET_LOCALE_SUCCESS,
  GET_SOCIALMEDIALINKS,
  GET_SOCIALMEDIALINKS_SUCCESS,
  ADD_NOTIFICATION,
  REMOVE_NOTIFICATION,
  GET_FORUM_BREADCRUMBS,
  GET_TOPIC_BREADCRUMBS,
  GET_BREADCRUMBS_SUCCESS
};
